[package]
name = "rustbio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
minifb = "0.27.0"

[profile.release]
debug = true
